### ISSUE TITLE
steps to train and test my own dataset

### ISSUE THREAD

**Issue by pohetsn** [jgmakin/rbmish#3] opened 2018-03-15 18:44 UTC
After reading the README.md, I still have some obstacles to use rETH to regress R (independent variables) to X (dependent variables).  Would you mind to give me some instructions to get it to work?

First I'd like to clarify meanings of a few parameters:
`numsUnits`, is the first element the number of features in R?
`Ncases`, what does case mean here? For example, is this number of cases for classification problem? and not needed for regression?
`Nbatches`, is it the number of short sequences to train for each epoch?  where the length of the sequence is specified?

Second, following the `polyphonicmusic` example, by using `getLatentNull`, I guess the `getDataPolyphonicMusic` needs to modified to load the two matrices (`R` and `X`) and return 3 variables: `R, X, Q`, and change `generateData.m` to return the 3 variables from `getData`.  Is that correct?

Third, which script to call for testing?  `Q` is empty at this moment, is there something I should add to the struct?  

Thank you.

**Comment by jgmakin** [comment] 2018-03-25 21:01
I think, but am not sure, that you may be misunderstanding something about the algorithm.  The *basic* algorithm is unsupervised, so not suitable for solving regression problems.  The reason that the code nevertheless allows for two sets of data, `R` and `X`...is complicated, but essentially it's to allow for two-step generative models of the actual training data, `R`: first `X` is produced from some prior distribution p(x), and then `R` is produced from an emission probability p(r|x).  Conceptually, these steps correspond to `getLatents` and `getData`, functions that you will write for your specific data set.  You can then throw away `X`, if you like, since the model tries to fit just the marginal distribution of p(r); i.e., it tries to minimize the KL divergence from p(r) to its own distribution, q(r; parameters).  Or you need not create it in the first place, e.g. if you are in the typical case of possessing just training samples `R`.  I've written a function, `getLatentNull`, for that common case: it just loads data `R` and never bothers to produce any data `X`.  (And I'll answer your third question here: `Q` is intended as a catch-all, a structure to store just whatever other useful stuff you create in the generative process.

Having said that, though, one can do regression in a more complicated context:  First train an rEFH on independent temporal variables `R_t`; then run inference to get some latent representation (call it `Z_t`); and then finally build a map (regression) from the latent variables `Z_t` to the dependent variables of interest.  These may indeed be `X_t`.  Is this what you have in mind?  There is code to do precisely this, although I haven't written that part of the readme yet.  

To your first question: Yes, the first element of `numUnits` should be the number of features in `R`.  The parameter `Ncases` is needed for all problems: it's the number of cases per (mini)batch, i.e. the number of training vectors that go into a single weight update.  Likewise, `Nbatches` is the number of batches (each consisting of `Ncases`) that constitutes an "epoch."  Typically in the literature (as you probably know), an epoch corresponds to a single pass through all the data, but here it's more precise to say that what happens once an epoch is a call to `generateData`--what exactly it produces is up to you, since you get to write its component functions, `getLatents` and `getData`.

How does sequence *length* enter into this?  First of all, it must be the same for all sequences (or "trajectories"--I use these terms interchangeably).  After that, you have a choice: you can either let each batch correspond to a *single trajectory* (`params.EACHBATCHISATRAJ = 1`), in which case each case within that batch is a different time step of that single trajectory; or you can let each batch correspond to a *single time step* of `Ncases` trajectories (`params.EACHBATCHISATRAJ = 0`).  I have found the latter to yield slightly better results in practice.

As for testing (your third question): You write your own test function in `params.testEFH`. That gets called by `EFHdisp` (which itself gets called once an epoch, although how often, in terms of epochs, that the test is run is controlled by `Ntest` in `DBNtrain`), but you can call it yourself anywhere of course.  You can see some examples of `params.testEFH` functions by looking in `setParams.m`.  What is appropriate depends on exactly what kind of problem you're trying to solve.  If you give me a little more detail, I can try to recommend something.

**Comment by jgmakin** [comment] 2018-05-12 00:58
Closing for want of activity.

**Closed as completed** 2018-05-12 00:58 UTC
